---
services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:3.77.2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - nexus-data:/nexus-data
    restart: always
  allowlist:
    container_name: allowlist
    image: nexus-allowlist
    build: .
    environment:
      NEXUS_ADMIN_PASSWORD: "password"
      NEXUS_PACKAGES: "selected"
      NEXUS_HOST: "nexus"
      NEXUS_PORT: "8081"
      # ENTR_FALLBACK: "yes"
    volumes:
      - ./allowlists:/allowlists
      - nexus-data:/nexus-data
    restart: always
  reverse-proxy:
    container_name: reverse-proxy
    image: caddy:2.8-alpine
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
volumes:
  nexus-data:
